In [6]:
import numpy as np


In [8]:
benimDizim=np.arange(0,15)

In [9]:
benimDizim


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
benimDizim[3:5]

array([3, 4])

In [11]:
benimDizim[3:8]= -5

In [12]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#elemanları değiştirdi kullanışlı 


In [14]:
baskaDizi = np.arange(0,24)



In [16]:
baskaDizi


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
sdizi = baskaDizi[3:9]

In [18]:
sdizi

array([3, 4, 5, 6, 7, 8])

In [19]:
#ikinci dize ayrı


In [23]:
#sdizi = 700# diziyi 700 yaptı
sdizi

700

In [24]:
#sdizi[:] = 700 #bütün elemanları 700 eşitler
sdizi

TypeError: 'int' object does not support item assignment

In [5]:
ornekDizi = np.arange(0,24)

NameError: name 'np' is not defined

In [31]:
#ornekKopya ornekDizi aynısını yazar

In [33]:
#ornekKopyaS= ornekKopya[3:6]  # 3 den sonra 6incı indekse kadar al

In [35]:
#ornekKopyaS[:]= 800 bütün elemanları 800 yaptık # kopyada da 800 oldu ama orjinalı bozmadık 

In [36]:
#MATRİX#



In [37]:
benimListemm= [[10,20,30],[40,66,88]]


In [38]:
benimMatris = np.array(benimListemm)

In [39]:
benimMatris

array([[10, 20, 30],
       [40, 66, 88]])

In [40]:
 # benimMatris[1:2] ile [1,2] aynı şey

In [41]:
#[2:,2]  0 1 2 yani 3. satırın 3. elemanı 


In [1]:
#[2:0,:] 2. satırdan 0.indexli elemandan itibaren yazar


In [3]:
yeniListe= [[0,2,3,4],[5,6,7,8],[10,11,12,15 ]]

In [7]:
yeniMatrix = np.array(yeniListe)

In [8]:
yeniMatrix

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 15]])

In [10]:
yeniMatrix[[0,2]]#iki kez parentez böyle olunca 0. ve  3 . satırı liste yazar

array([[ 0,  2,  3,  4],
       [10, 11, 12, 15]])

In [11]:
##operasyonlar##


In [16]:
yeniDizi = np.random.randint(1,100,20)

In [17]:
yeniDizi

array([23, 77, 48,  5, 16, 45, 95, 33,  4, 68, 51, 55, 14,  8, 61,  5, 86,
       81, 72, 45])

In [18]:
yeniDizi>24

array([False,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True, False, False,  True, False,  True,  True,
        True,  True])

In [19]:
sonucDizi = yeniDizi > 24

In [20]:
yeniDizi[sonucDizi]

array([77, 48, 45, 95, 33, 68, 51, 55, 61, 86, 81, 72, 45])

In [22]:
yeniDizi[yeniDizi>24] # böylede olr

array([77, 48, 45, 95, 33, 68, 51, 55, 61, 86, 81, 72, 45])

In [24]:
sondizi = np.arange(0,24)

In [26]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
sondizi + sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [28]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [29]:
#işlemler yukrd#

In [30]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [31]:
#karekokalma#

In [32]:
np.max(sondizi)

23